### ISSUE TITLE
Please, add a feature to keep max framerate too (preferrably to the one chosen in the config).

### ISSUE THREAD

**Issue by Nordblum** [inkyarev/keep-my-settings#1]
Unity's built-in framerate limiter is awful. I limit my FPS using NVidia app to 70, just above my monitor's 60 Hz. All the games look great and smooth this way without needing to render hundreds of frames for diminishing returns, keeping the GPU cool (and good). Every time I launch RoR 2, I have to change "Max Framerate" from 60 (which is default for some reason even after a fresh reinstall) to "Unlimited". First I thought is was some mod that caused this setting to reset every time I quit the game. Tried launching the game with no mods at all. Didn't help. Tried changing it in config.cfg, in autoexec.cfg, making both of these read-only. Nothing worked. Every time I launch the game, "Max Framerate" is back to 60. Please, if you can, add an option to also KeepMyFramerate.

**Comment by inkyarev** [comment]
added with 6b536c580f40225d25bc3a9899d9579595b95a1f(and kinda aadd66a2e73ddb3fae2eebeda0b666310962b5ca)
i'll create a new release and update the thunderstore package soon
